//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkoutForces.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Challenge
    {
        public string Id { get; set; }
        public Nullable<System.DateTime> TimePost { get; set; }
        public Nullable<System.DateTime> TimeEnd { get; set; }
        public string Content { get; set; }
        public Nullable<int> IdUser { get; set; }
    }
}
